name: Publish to nuget
on:
  push:
    branches:
      - master # Your default release branch
jobs:
  publish:
    name: publish to nuget
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
        
      # Publish
      - name: Publish NuGet
        uses: rohith/publish-nuget@v1.2.0
        with:
           project_dir: Serilog.Sanitizer
           tag_format: v*
           nuget_key: ${{secrets.NUGET_API_KEY}}
